use std::collections::LinkedList;
use std::fs::File;
use std::io::prelude::*;
use std::cmp;

use crate::quad_tree::WCoord;

pub struct InputState {
    pub is_paused: bool,
    pub show_grid: bool
}

impl InputState {
    pub fn new() -> Self {
        InputState {
            is_paused: true,
            show_grid: false
        }
    }
}

fn format_output_path(path: Option<&String>) -> String {
    // TODO: add more sophisticated formatting in here
    path.map_or(String::from("assets/patterns/default.rle"), |v| (*v).clone())
}

pub fn save_pattern(cells: &LinkedList<WCoord>, arg: Option<&String>, b: &Vec<usize>, s: &Vec<usize>) -> std::io::Result<()> {
    let mut init = String::new();
    init.push_str(&"#C Generated by github.com/favalosdev/game-of-life\n");
    init.push_str(&encode_run_length(cells, b, s));
    
    // Create file and write
    let path = format_output_path(arg);
    let mut file = File::create(path).unwrap();
    file.write_all(init.as_bytes()).unwrap();

    Ok(())
}

fn encode_run_length(cells: &LinkedList<WCoord>, b: &Vec<usize>, s: &Vec<usize>) -> String {
    // Do something costly in here
    let mut body = String::new();

    /* STEPS:
    1. Calculate bounding box
    2. Iterate and aggregate information accordingly
    */

    let mut aux = (*cells).clone().into_iter().collect::<Vec<WCoord>>();
    let n = aux.len();

    if n == 0 {
        return String::from("!");
    }

    aux.sort_by(|a,  b| b.1.cmp(&a.1).then(a.0.cmp(&b.0)));

    let mut xs = aux.iter().map(|c| c.0).collect::<Vec<isize>>();
    xs.sort_by(|a, b| a.cmp(b));

    let min_x = xs[0];
    let max_x = *(xs.last().unwrap());

    let min_y = aux.last().unwrap().1;
    let max_y = aux[0].1;

    let span_x = max_x - min_x + 1;
    let span_y = max_y - min_y + 1;

    body.push_str(
        &format!(
            "x = {}, y = {}, rule = B{}/S{}\n",
            span_x,
            span_y,
            b.iter().map(|n| n.to_string()).collect::<String>(),
            s.iter().map(|n| n.to_string()).collect::<String>())
    );

    body.push_str(&"!");
    body
}
