use std::collections::LinkedList;
use std::fs::File;
use std::io::prelude::*;
use std::cmp;

use crate::quad_tree::WCoord;

pub struct InputState {
    pub is_paused: bool,
    pub show_grid: bool
}

impl InputState {
    pub fn new() -> Self {
        InputState {
            is_paused: true,
            show_grid: false
        }
    }
}

fn format_output_path(path: Option<&String>) -> String {
    // TODO: add more sophisticated formatting in here
    path.map_or(String::from("assets/patterns/default.rle"), |v| (*v).clone())
}

pub fn save_pattern(cells: &LinkedList<WCoord>, arg: Option<&String>, b: &Vec<usize>, s: &Vec<usize>) -> std::io::Result<()> {
    let mut init = String::new();
    init.push_str(&"#C Generated by github.com/favalosdev/game-of-life\n");
    init.push_str(&get_rle_string(cells, b, s));
    
    // Create file and write
    let path = format_output_path(arg);
    let mut file = File::create(path).unwrap();
    file.write_all(init.as_bytes()).unwrap();

    Ok(())
}

fn get_rle_string(cells: &LinkedList<WCoord>, b: &Vec<usize>, s: &Vec<usize>) -> String {
    // Do something costly in here
    let mut body = String::new();

    /*
    let mut aux: Vec<WCoord> = (*cells).clone().into_iter().collect();
    let n = aux.len();

    if n == 0 {
        return String::from("!");
    }

    aux.sort_by(|a, b| a.0.cmp(&b.0).then(a.1.cmp(&b.1)));

    let mut last = aux[0];
    let mut counter = 1;

    let min_x = last.0;
    let mut max_x = min_x;
    let mut min_y = isize::MAX;
    let mut max_y = isize::MIN;

    let mut i = 1;

    let mut body = String::new();

    while i < n {
        let curr = aux[i];

        max_x = cmp::max(max_x, curr.0);
        min_y = cmp::min(min_y, curr.1);
        max_y = cmp::max(max_y, curr.1);

        if last.0 != curr.0 {
            if counter > 1 {
                body.push_str(&format!("{}", counter));
            }

            body.push_str(&"o");

            // Mark end of line
            body.push_str(&"$");

            counter = 1;
        } else {
            let diff = curr.1 - last.1 - 1;

            if diff > 0 {
                body.push_str(&format!("{}b", diff));

                if counter > 1 {
                    body.push_str(&format!("{}", counter));
                }

                body.push_str(&"o");

                counter = 1;
            } else {
                counter += 1;
            }
        }

        last = curr;
        i += 1;
    }

    if counter > 1 {
        body.push_str(&format!("{}", counter));
    }

    body.push_str(&"o");
    */
    body.push_str(&"!");
    body
}

