use std::collections::LinkedList;
use std::fs::File;
use std::io::prelude::*;

use crate::quad_tree::WCoord;

pub struct InputState {
    pub is_paused: bool,
    pub show_grid: bool
}

impl InputState {
    pub fn new() -> Self {
        InputState {
            is_paused: true,
            show_grid: false
        }
    }
}

fn format_output_path(path: Option<&String>) -> String {
    // TODO: add more sophisticated formatting in here
    path.map_or(String::from("assets/patterns/default.rle"), |v| (*v).clone())
}

pub fn save_pattern(cells: &LinkedList<WCoord>, arg: Option<&String>, b: &Vec<usize>, s: &Vec<usize>) -> std::io::Result<()> {
    let mut init = String::from("#C Generated by github.com/favalosdev/game-of-life\n");
    init.push_str(&get_rle_string(cells, b, s));
    
    // Create file and write
    let path = format_output_path(arg);
    let mut file = File::create(path).unwrap();
    file.write_all(init.as_bytes()).unwrap();

    Ok(())
}

fn get_rle_string(cells: &LinkedList<WCoord>, b: &Vec<usize>, s: &Vec<usize>) -> String {
    // Do something costly in here
    let mut copy: Vec<WCoord> = (*cells).clone().into_iter().collect();

    // Source - https://stackoverflow.com/a/76301320
    // Posted by user2722968
    // Retrieved 2026-03-16, License - CC BY-SA 4.0

    copy.sort_by(|a, b| {
        a.0.cmp(&b.0).then(a.1.cmp(&b.1))
    });

    let x = 0;
    let y = 0;

    String::from("dummy")
}
