use std::collections::HashSet;
use std::fs::File;
use std::io::prelude::*;
use std::fs;

use ca_formats::Coordinates;
use chrono::Local;

fn get_min_max(values: &Vec<i64>) ->(i64, i64) {
    let mut min = *(values.first().unwrap());
    let mut max = min;

    for &v in values {
        min = min.min(v);
        max = max.max(v);
    }

    (min, max)
}

fn get_bounding_box(cells: &Vec<Coordinates>) -> (i64, i64, i64, i64) {
    let x_coords: Vec<i64> = cells.into_iter().map(|c| c.0).collect();
    let y_coords: Vec<i64> = cells.into_iter().map(|c| c.1).collect();

    let (min_x, max_x) = get_min_max(&x_coords);
    let (min_y, max_y) = get_min_max(&y_coords);

    (min_x, max_x, min_y, max_y)
}

fn write_run(body: &mut String, counter: i32, alive: bool) {
    if counter > 1 {
        body.push_str(format!("{}", counter).as_str());
    }

    body.push_str(if alive { "o" } else { "b" });
}

fn encode_run_length(cells: &Vec<Coordinates>, b: &Vec<u8>, s: &Vec<u8>) -> Result<String, Box<dyn std::error::Error>> {
    let mut body = String::new();

    let mut span_x = 0;
    let mut span_y = 0;
    let mut min_x = 0;
    let mut max_x = 0;
    let mut min_y = 0;
    let mut max_y = 0;

    if !cells.is_empty() {
        (min_x, max_x, min_y, max_y) = get_bounding_box(cells);
        span_x = max_x - min_x + 1;
        span_y = max_y - min_y + 1;
    }

    body.push_str(
        format!(
            "x = {}, y = {}, rule = B{}/S{}\n",
            span_x,
            span_y,
            b.iter().map(|n| n.to_string()).collect::<String>(),
            s.iter().map(|n| n.to_string()).collect::<String>()).as_str()
    );

    let lookup: HashSet<Coordinates> = cells.iter().cloned().collect();
    
    for y in (min_y..=max_y).rev() {
        let mut counter = 1;
        let mut last: bool = lookup.contains(&(min_x, y));

        for x in (min_x+1)..=max_x {
            let curr = lookup.contains(&(x, y));

            if curr != last {
                write_run(&mut body, counter, last);
                counter = 1;
            } else {
                counter += 1;
            }

            last = curr;
        }

        if last {
            write_run(&mut body, counter, true);
        }

        body.push_str(if y > min_y { "$" } else { "!" });
    } 

    Ok(body)
}

fn generate_path() -> Result<String, std::io::Error> {
    let dir = "results";
    fs::create_dir_all(dir)?;

    let ts = Local::now().format("%Y%m%d_%H%M%S");

    Ok(format!("{}/gol_{}.rle", dir, ts))
}

pub fn save_pattern(
    cells: &Vec<Coordinates>,
    path: Option<&String>,
    b: &Vec<u8>,
    s: &Vec<u8>
) -> Result<(), Box<dyn std::error::Error>> {
    let mut init = String::new();
    init.push_str("#C Generated by github.com/favalosdev/golfront\n");

    let rle = encode_run_length(cells, b, s)?;
    
    for chunk in rle.as_bytes().chunks(70) {
        let s = std::str::from_utf8(chunk)?;
        init.push_str(format!("{}\n", s).as_str());
    }

    let filename = match path {
        Some(s) => s.clone(),
        None => generate_path()?,
    }; 

    let mut file = File::create(filename)?;
    file.write_all(init.as_bytes())?;

    Ok(())
}
