use std::collections::{LinkedList, HashSet};
use std::fs::File;
use std::io::prelude::*;
use std::fs;
use std::cmp;

use chrono::Local;

use golback::universe::WCoord;

fn get_min_max(values: &LinkedList<isize>) -> Result<(isize, isize), &'static str> {
    if values.is_empty() {
        return Err("Values must not be empty");
    }

    let mut min = *values.front().unwrap();
    let mut max = min;

    for &v in values {
        min = cmp::min(min, v);
        max = cmp::max(max, v);
    }

    Ok((min, max))
}

fn get_bounding_box(cells: &LinkedList<WCoord>) -> Result<(isize, isize, isize, isize), &'static str> {
    let x_coords: LinkedList<isize> = cells.iter().map(|c| c.0).collect();
    let y_coords: LinkedList<isize> = cells.iter().map(|c| c.1).collect();

    let (min_x, max_x) = get_min_max(&x_coords)?;
    let (min_y, max_y) = get_min_max(&y_coords)?;

    Ok((min_x, max_x, min_y, max_y))
}

fn write_run(body: &mut String, counter: i32, alive: bool) {
    if counter > 1 {
        body.push_str(&format!("{}", counter));
    }

    body.push_str(if alive { "o" } else { "b" });
}

fn encode_run_length(cells: &LinkedList<WCoord>, b: &Vec<usize>, s: &Vec<usize>) -> Result<String, Box<dyn std::error::Error>> {
    let mut body = String::new();

    let (min_x, max_x, min_y, max_y) = get_bounding_box(cells)?;
    let span_x = max_x - min_x + 1;
    let span_y = max_y - min_y + 1;

    body.push_str(
        &format!(
            "x = {}, y = {}, rule = B{}/S{}\n",
            span_x,
            span_y,
            b.iter().map(|n| n.to_string()).collect::<String>(),
            s.iter().map(|n| n.to_string()).collect::<String>())
    );

    let lookup: HashSet<WCoord> = cells.iter().cloned().collect();
    
    for y in (min_y..=max_y).rev() {
        let mut counter = 1;
        let mut last: bool = lookup.contains(&(min_x, y));

        for x in (min_x+1)..=max_x {
            let curr = lookup.contains(&(x, y));

            if curr != last {
                write_run(&mut body, counter, last);
                counter = 1;
            } else {
                counter += 1;
            }

            last = curr;
        }

        if last {
            write_run(&mut body, counter, true);
        }

        body.push_str(if y > min_y { "$" } else { "!" });
    } 

    Ok(body)
}

fn format_output_path(path: Option<&String>) -> Result<String, std::io::Error> {
    if let Some(p) = path {
        return Ok(p.clone());
    }

    let dir = "results";
    fs::create_dir_all(dir)?;

    let ts = Local::now().format("%Y%m%d_%H%M%S");
    let formatted = format!("{}/gol_{}.rle", dir, ts);

    Ok(formatted)
}

pub fn save_pattern(
    cells: &LinkedList<WCoord>,
    path: Option<&String>,
    b: &Vec<usize>,
    s: &Vec<usize>
) -> Result<(), Box<dyn std::error::Error>> {
    let mut init = String::new();

    init.push_str(&"#C Generated by github.com/favalosdev/game-of-life\n");

    let rle = encode_run_length(cells, b, s)?;
    
    for chunk in rle.as_bytes().chunks(70) {
        let s = std::str::from_utf8(chunk)?;
        init.push_str(&format!("{}\n", s));
    }

    let path = format_output_path(path)?;
    let mut file = File::create(&path)?;
    file.write_all(init.as_bytes())?;

    Ok(())
}
